
name: Deploy to workspace
on: [pull_request]
jobs:
  Deploy-Asset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          separator: ","
          quotepath: false
      - name: Power BI Workspace Deploy
        uses: nathangiusti/Power-BI-Workspace-Deploy@v1.2
        with:
          files: ${{ steps.changed-files.outputs.all_modified_files }}
          separator: ","
          tenant_id: ${{ secrets.TENANT_ID }}
          config_file: ".github/config/workspace-deploy-config.yaml"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
